version: '3.8'

services:
  nexterm:
    build: .
    container_name: nexterm
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./sessions:/app/sessions
    networks:
      - nexterm_net

networks:
  nexterm_net:
    driver: bridge
    name: nexterm_net
